-- ============================================
-- DROP EXISTING (agar kerak bo'lsa)
-- ============================================
DROP TABLE IF EXISTS appointments CASCADE;
DROP TABLE IF EXISTS staff_services CASCADE;
DROP TABLE IF EXISTS employements CASCADE;
DROP TABLE IF EXISTS staff_schedules CASCADE;
DROP TABLE IF EXISTS staff CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ============================================
-- USERS TABLE
-- ============================================
CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name    VARCHAR(100)                            NOT NULL,
    last_name     VARCHAR(100)                            NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    phone         VARCHAR(20)                             NOT NULL,
    status        VARCHAR(20)                             NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uc_users_email UNIQUE (email)
);

CREATE INDEX idx_users_email ON users (email);
CREATE INDEX idx_users_status ON users (status);

COMMENT ON TABLE users IS 'Tizim foydalanuvchilari (staff login uchun)';
COMMENT ON COLUMN users.password_hash IS 'BCrypt hash';
COMMENT ON COLUMN users.status IS 'ACTIVE, INACTIVE, BLOCKED';

-- ============================================
-- TENANTS TABLE
-- ============================================
CREATE TABLE tenants
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_key           VARCHAR(36)                             NOT NULL,
    slug                 VARCHAR(100)                            NOT NULL,
    business_type        VARCHAR(50)                             NOT NULL,
    organization_name    VARCHAR(200)                            NOT NULL,
    email                VARCHAR(255)                            NOT NULL,
    phone                VARCHAR(20)                             NOT NULL,
    address              VARCHAR(500)                            NOT NULL,
    working_hours_start  TIME WITHOUT TIME ZONE                  NOT NULL,
    working_hours_end    TIME WITHOUT TIME ZONE                  NOT NULL,
    slot_duration        INTEGER                                 NOT NULL,
    advance_booking_days INTEGER                                 NOT NULL,
    auto_confirm_booking BOOLEAN                                 NOT NULL,
    timezone             VARCHAR(50)                             NOT NULL,
    is_active            BOOLEAN                                 NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,

    CONSTRAINT pk_tenants PRIMARY KEY (id),
    CONSTRAINT uc_tenants_tenant_key UNIQUE (tenant_key),
    CONSTRAINT uc_tenants_slug UNIQUE (slug),
    CONSTRAINT chk_slot_duration CHECK (slot_duration > 0),
    CONSTRAINT chk_advance_days CHECK (advance_booking_days > 0)
);

CREATE INDEX idx_tenants_slug ON tenants (slug);
CREATE INDEX idx_tenants_is_active ON tenants (is_active);
CREATE INDEX idx_tenants_business_type ON tenants (business_type);

COMMENT ON TABLE tenants IS 'Organizatsiyalar (Multi-tenant)';
COMMENT ON COLUMN tenants.tenant_key IS 'Backend identifier (UUID)';
COMMENT ON COLUMN tenants.slug IS 'URL: myapp.uz/{slug}';
COMMENT ON COLUMN tenants.slot_duration IS 'Minutlarda (30, 60, etc)';

-- ============================================
-- STAFF TABLE
-- ============================================
CREATE TABLE staff
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id    BIGINT                                  NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    role         VARCHAR(20)                             NOT NULL,
    display_name VARCHAR(100)                            NOT NULL,
    position     VARCHAR(100)                            NOT NULL,
    is_active    BOOLEAN                                 NOT NULL,
    joined_at    TIMESTAMP WITHOUT TIME ZONE                     ,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,

    CONSTRAINT pk_staff PRIMARY KEY (id),
    CONSTRAINT fk_staff_tenant FOREIGN KEY (tenant_id)
        REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT fk_staff_user FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX idx_staff_tenant ON staff (tenant_id);
CREATE INDEX idx_staff_user ON staff (user_id);
CREATE INDEX idx_staff_is_active ON staff (tenant_id, is_active);
CREATE INDEX idx_staff_role ON staff (tenant_id, role);

COMMENT ON TABLE staff IS 'Organizatsiya xodimlari';
COMMENT ON COLUMN staff.role IS 'OWNER, ADMIN, MANAGER, STAFF';

-- ============================================
-- STAFF SCHEDULES TABLE
-- ============================================
CREATE TABLE staff_schedules
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    staff_id     BIGINT                                  NOT NULL,
    day_of_week  INTEGER                                 NOT NULL,
    start_time   TIME WITHOUT TIME ZONE,
    end_time     TIME WITHOUT TIME ZONE,
    is_available BOOLEAN                                 NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,

    CONSTRAINT pk_staff_schedules PRIMARY KEY (id),
    CONSTRAINT fk_staff_schedules_staff FOREIGN KEY (staff_id)
        REFERENCES staff (id) ON DELETE CASCADE,
    CONSTRAINT uc_staff_schedules_staff_day UNIQUE (staff_id, day_of_week),
    CONSTRAINT chk_day_of_week CHECK (day_of_week >= 1 AND day_of_week <= 7),
    CONSTRAINT chk_schedule_times CHECK (
        (is_available = false) OR
        (is_available = true AND start_time IS NOT NULL AND end_time IS NOT NULL AND end_time > start_time)
        )
);

CREATE INDEX idx_staff_schedules_staff ON staff_schedules (staff_id);
CREATE INDEX idx_staff_schedules_day ON staff_schedules (day_of_week, is_available);

COMMENT ON TABLE staff_schedules IS 'Xodimlarning haftalik ish jadvali';
COMMENT ON COLUMN staff_schedules.day_of_week IS '1=Dushanba, 2=Seshanba, ..., 7=Yakshanba';

-- ============================================
-- SERVICES TABLE
-- ============================================
CREATE TABLE employements
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id     BIGINT                                  NOT NULL,
    name          VARCHAR(200)                            NOT NULL,
    description   TEXT,
    duration      INTEGER                                 NOT NULL,
    price         DECIMAL(10, 2)                          NOT NULL,
    image_url     VARCHAR(500),
    is_active     BOOLEAN                                 NOT NULL,
    display_order INTEGER,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,

    CONSTRAINT pk_services PRIMARY KEY (id),
    CONSTRAINT fk_services_tenant FOREIGN KEY (tenant_id)
        REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT chk_duration CHECK (duration > 0),
    CONSTRAINT chk_price CHECK (price >= 0)
);

CREATE INDEX idx_services_tenant ON employements (tenant_id);
CREATE INDEX idx_services_is_active ON employements (tenant_id, is_active);
CREATE INDEX idx_services_display_order ON employements (tenant_id, display_order);

COMMENT ON TABLE employements IS 'Xizmatlar (soch turmaklash, tish tozalash, etc)';
COMMENT ON COLUMN employements.duration IS 'Minutlarda';
COMMENT ON COLUMN employements.image_url IS 'Rasm URL (ko''p rasm: url1,url2,url3)';

-- ============================================
-- STAFF SERVICES (Junction Table)
-- ============================================
CREATE TABLE staff_services
(
    staff_id   BIGINT NOT NULL,
    service_id BIGINT NOT NULL,

    CONSTRAINT pk_staff_services PRIMARY KEY (staff_id, service_id),
    CONSTRAINT fk_staff_services_staff FOREIGN KEY (staff_id)
        REFERENCES staff (id) ON DELETE CASCADE,
    CONSTRAINT fk_staff_services_service FOREIGN KEY (service_id)
        REFERENCES employements (id) ON DELETE CASCADE
);

CREATE INDEX idx_staff_services_staff ON staff_services (staff_id);
CREATE INDEX idx_staff_services_service ON staff_services (service_id);

COMMENT ON TABLE staff_services IS 'Staff va Employement ManyToMany relationship';

-- ============================================
-- APPOINTMENTS TABLE
-- ============================================
CREATE TABLE appointments
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tenant_id        BIGINT                                  NOT NULL,
    staff_id         BIGINT                                  NOT NULL,
    service_id       BIGINT                                  NOT NULL,
    customer_name    VARCHAR(100)                            NOT NULL,
    customer_phone   VARCHAR(20)                             NOT NULL,
    customer_email   VARCHAR(255),
    appointment_date DATE                                    NOT NULL,
    start_time       TIME WITHOUT TIME ZONE                  NOT NULL,
    end_time         TIME WITHOUT TIME ZONE                  NOT NULL,
    status           VARCHAR(20)                             NOT NULL,
    total_price      DECIMAL(10, 2)                          NOT NULL,
    notes            TEXT,
    created_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    confirmed_at     TIMESTAMP WITHOUT TIME ZONE,
    completed_at     TIMESTAMP WITHOUT TIME ZONE,
    cancelled_at     TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT pk_appointments PRIMARY KEY (id),
    CONSTRAINT fk_appointments_tenant FOREIGN KEY (tenant_id)
        REFERENCES tenants (id) ON DELETE CASCADE,
    CONSTRAINT fk_appointments_staff FOREIGN KEY (staff_id)
        REFERENCES staff (id) ON DELETE CASCADE,
    CONSTRAINT fk_appointments_service FOREIGN KEY (service_id)
        REFERENCES employements (id) ON DELETE RESTRICT,
    CONSTRAINT chk_appointment_time CHECK (end_time > start_time),
    CONSTRAINT chk_total_price CHECK (total_price >= 0)
);

CREATE INDEX idx_appointments_tenant_date ON appointments (tenant_id, appointment_date);
CREATE INDEX idx_appointments_staff_date ON appointments (staff_id, appointment_date);
CREATE INDEX idx_appointments_status ON appointments (status);
CREATE INDEX idx_appointments_customer_phone ON appointments (customer_phone);
CREATE INDEX idx_appointments_date_time ON appointments (appointment_date, start_time);

COMMENT ON TABLE appointments IS 'Uchrashuvlar/Navbatlar';
COMMENT ON COLUMN appointments.status IS 'PENDING, CONFIRMED, CANCELLED, COMPLETED, NO_SHOW';

-- ============================================
-- SAMPLE DATA (Test uchun)
-- ============================================

-- User
INSERT INTO users (first_name, last_name, email, password_hash, phone, status, created_at, updated_at)
VALUES ('Ali', 'Valiyev', 'ali@example.com', '$2a$10$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        '+998901234567', 'ACTIVE', NOW(), NOW());

-- Tenant
INSERT INTO tenants (tenant_key, slug, business_type, organization_name, email, phone, address,
                     working_hours_start, working_hours_end, slot_duration, advance_booking_days,
                     auto_confirm_booking, timezone, is_active, created_at, updated_at)
VALUES ('550e8400-e29b-41d4-a716-446655440000', 'style-barbershop', 'BARBERSHOP',
        'Style Barbershop', 'info@style.uz', '+998901111111', 'Toshkent, Amir Temur 1',
        '09:00', '18:00', 30, 30, false, 'Asia/Tashkent', true, NOW(), NOW());

-- Staff
INSERT INTO staff (tenant_id, user_id, role, display_name, position, is_active, joined_at, created_at, updated_at)
VALUES (1, 1, 'OWNER', 'Ali aka', 'Senior Sartarosh', true, NOW(), NOW(), NOW());

-- Employement
INSERT INTO employements (tenant_id, name, description, duration, price, is_active, display_order, created_at, updated_at)
VALUES (1, 'Soch turmaklash', 'Klassik soch turmaklash', 30, 50000.00, true, 1, NOW(), NOW());

-- Staff Schedule (Dushanba)
INSERT INTO staff_schedules (staff_id, day_of_week, start_time, end_time, is_available, created_at, updated_at)
VALUES (1, 1, '09:00', '18:00', true, NOW(), NOW());